# Datasource (Render PostgreSQL)
spring.datasource.url=jdbc:postgresql://dpg-d5h49cmr433s73bgup80-a.oregon-postgres.render.com:5432/ems_postgres_ei53?sslmode=require
spring.datasource.username=ems_postgres_ei53_user
spring.datasource.password=uwyEax23ATfZ6emCVx7wq9r6H3rtqpWA

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=${PORT:8080}
